name: Pull Request Test

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Log Message
      run: |
        echo "This is a Pull Request Workflow"
        echo "Running with Github Actions"

