name: Eduardo - Automatic - Environment Variables

# Defines that this workflow is triggered manually
# Manual Trigger on Push, Pull Request, or Schedule
on: [push]

jobs:
  Run-Repo:
    runs-on: ubuntu-latest
    steps:
      - name: Echo Message
        run: echo "Hello, GitHub Actions!"
      - name: Print Repository Repository Variable
        run: |
          echo "GITHUB_REPOSITORY SECRET: ${{ secrets.TEST_REPO_SECRET }}"
          echo "GITHUB_REPOSITORY VAR: ${{ vars.TEST_REPO_VAR }}"
      - name: End Exeecution
        run: echo "End of Execution"

  Run-Env:
    runs-on: ubuntu-latest
    environment: Morita-Development
    steps:
      - name: Echo Message
        run: echo "Hello, GitHub Actions!"
      - name: Print Repository Environment Variable
        run: |
          echo "GITHUB_REPOSITORY SECRET: ${{ secrets.TEST_REPO_SECRET }}"
          echo "GITHUB_REPOSITORY VAR: ${{ vars.TEST_REPO_VAR }}"
      - name: End Exeecution
        run: echo "End of Execution"

