name: Eduardo - Simple Automatic

# Defines that this workflow is triggered manually
# Manual Trigger on Push, Pull Request, or Schedule
on: [push]

jobs:
  Run-Simple:
    runs-on: ubuntu-latest
    steps:
      - name: Echo Message
        run: echo "Hello, GitHub Actions!"

