# Create Workflow to Run Node Script
name: Manual Node Simple

on: [workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install Dependencies
        run: |
          echo "Installing Dependencies"
          cd .github/supplementary/node-simple
          npm ci
          echo "Dependencies Installed"

      - name: Run Script
        run: |
          echo "Ready to Start Node App"
          node .github/supplementary/node-simple/index.js
          echo "Node App Started"
